CREATE TABLE IF NOT EXISTS tweet (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    reply_to_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
