// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package tutorial

import (
	"context"
)

// iteratorForBulkInsertTweetImage implements pgx.CopyFromSource.
type iteratorForBulkInsertTweetImage struct {
	rows                 []BulkInsertTweetImageParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertTweetImage) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertTweetImage) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TweetID,
		r.rows[0].ImageUrl,
	}, nil
}

func (r iteratorForBulkInsertTweetImage) Err() error {
	return nil
}

func (q *Queries) BulkInsertTweetImage(ctx context.Context, arg []BulkInsertTweetImageParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tweet_images"}, []string{"tweet_id", "image_url"}, &iteratorForBulkInsertTweetImage{rows: arg})
}
