// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerifyToken struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Tweet struct {
	ID        int32
	UserID    string
	Content   pgtype.Text
	ImgUrl    pgtype.Text
	ReplyToID pgtype.Text
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID       string
	Name     string
	Email    string
	Password string
	IsActive pgtype.Bool
}
